import { Inter } from 'next/font/google'
// import './ui/globals.css'

import Sidebar from '../ui/dashboard/sidebar/Sidebar'
import Navebar from '../ui/dashboard/Navebar/Navebar'
import styles from '../ui/dashboard/dashboard.module.css'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <div className={styles.container}>
    {/* <html lang="en"> */}
    {/* <body className={inter.className}> */}
        <div className={styles.menu}>
        <Sidebar/>
        </div>
        <div className={styles.content}>
      <Navebar/>
      {children}
      </div>
      {/* </body> */}

    {/* </html> */}
    </div>

  
  )
}
